import { Kanit } from "next/font/google";
import "./globals.css";
const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Recipes App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${kanit.variable} antialiased`}>{children}</body>
    </html>
  );
}
